# Site settings
title: cya blog
SEOTitle: cya blog
header-img: img/home-bg.jpg
email: cyadxx@mail.ustc.edu.cn
# description: "关于程序与设计、黑客与画家 | 黄玄，Web & Mobile Lover，Software Engineer，UX Designer | 这里是 @Hux黄玄 的个人博客，与你一起发现更大的世界。"
# keyword: "黄玄, Hux黄玄, Hux, 鬼栈, huxpro, @huxpro, 黄玄的博客, Hux Blog, 博客, 个人网站, 互联网, Web, JavaScript, 前端, 设计"
url: "https://yuangcao.github.io" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username:     huxpro
# zhihu_username:     huxpro
github_username:    yuangcao
# twitter_username:   huxpro
# facebook_username:  huxpro
# linkedin_username:  firstname-lastname-idxxxx
email_address:  cyadxx@mail.ustc.edu.cn



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
# timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: yuangcao

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1' # Format: UA-xxxxxx-xx
ga_domain: yuangcao.github.io



# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "A graduate CS student at University of Science and Technology of China."
sidebar-avatar: /img/profile-photo.jpg # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
# friends: [
#     {
#         title: "乱序（Midare）",
#         href: "http://mida.re/"
#     },{
#         title: "Sherry Woo",
#         href: "https://sherrywoo.me/"
#     },{
#         title: "Kun Qian",
#         href: "http://kunq.me"
#     }
# ]
